### ISSUE TITLE
没有返回数据

### ISSUE THREAD

**Issue by 195680144195** [smallXueTu/Rcon#6]
2022-06-29 12:59:13 E/main: Exception in coroutine <unnamed>
java.lang.IllegalArgumentException: message is empty
        at net.mamoe.mirai.internal.contact.GroupImpl.sendMessage(GroupImpl.kt:183)
        at net.mamoe.mirai.contact.Group.sendMessage$suspendImpl(Group.kt:192)
        at net.mamoe.mirai.contact.Group.sendMessage(Group.kt)
        at rcon-2.0.1.mirai.jar//cn.ltcraft.rcon.Listener$registerEvents$1.invokeSuspend(Listener.kt:28)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

是用的https://github.com/orblazer/bungee-rcon 这个插件在bc上用的，也可能是那个插件自己的问题，

**Comment by smallXueTu** [comment]
正常的Rcon协议是没有问题的，可能这个rcon插件只能接收命令，不会返回命令的结果。

**Comment by 195680144195** [comment]
> 

并不，有一些插件的 指令有返回，但是有一些插件没有返回，经过测试，子服的服务端偶尔也会无返回

**Comment by 195680144195** [comment]
> 正常的Rcon协议是没有问题的，可能这个rcon插件只能接收命令，不会返回命令的结果。

2022-07-07 19:54:25 V/Bot.2677207706: Group(686395138) <- 执行完成，服务器无返回！
2022-07-07 19:54:25 E/main: Exception in coroutine <unnamed>
java.lang.IllegalArgumentException: message is empty
        at net.mamoe.mirai.internal.contact.GroupImpl.sendMessage(GroupImpl.kt:183)
        at net.mamoe.mirai.contact.Group.sendMessage$suspendImpl(Group.kt:192)
        at net.mamoe.mirai.contact.Group.sendMessage(Group.kt)
        at rcon-2.0.1.mirai.jar//cn.ltcraft.rcon.Listener$registerEvents$1.invokeSuspend(Listener.kt:28)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

用paper端还是一样的结果，

**Comment by smallXueTu** [comment]
> Author
> ### [<img alt="@msls1441" width="20" height="20" src="https://avatars.githubusercontent.com/u/68938017?s=60&amp;v=4">](/msls1441) ** [msls1441](/msls1441) ** commented [2分钟前](#issuecomment-1177492928)

你执行的命令是不是本来就无返回结果？

**Comment by 195680144195** [comment]
> > 作者
> > ### [<img alt="@msls1441" width="20" height="20" src="https://avatars.githubusercontent.com/u/68938017?s=60&amp;v=4">](/msls1441) ** [msls1441](/msls1441) ** 评论 [2分钟前](#issuecomment-1177492928)
> 
> 你执行的命令是不是本来就无返回结果？

不是，我执行lp info 没有返回

**Comment by smallXueTu** [comment]
> > > 作者
> > > ### [<img alt="@msls1441" width="20" height="20" src="https://avatars.githubusercontent.com/u/68938017?s=60&amp;v=4">](/msls1441) ** [msls1441](/msls1441) ** 评论 [2分钟前](#issuecomment-1177492928)
> > 
> > 
> > 你执行的命令是不是本来就无返回结果？
> 
> 不是，我执行lp info 没有返回

可以尝试执行help或者ver看看是否有返回结果 可能pl info这个命令是返回结果是打印到控制台的

**Comment by 195680144195** [comment]
> > > > 作者
> > > > ### [<img alt="@msls1441" width="20" height="20" src="https://avatars.githubusercontent.com/u/68938017?s=60&amp;v=4">](/msls1441) ** [msls1441](/msls1441) ** 评论 [2分钟前](#issuecomment-1177492928)
> > > 
> > > 
> > > 你执行的命令是不是本来就无返回结果？
> > 
> > 
> > 不是，我执行lp info 没有返回
> 
> 可以尝试执行help或者ver看看是否有返回结果 可能pl info这个命令是返回结果是打印到控制台的

有一些指令可以返回结果，这个也不是打印到控制台的，很多指令都无法返回结果，

**Comment by smallXueTu** [comment]
> 

有些插件的消息信息可能不是通过CommandSender#sendMessage发送的。导致执行结果不会被返回..另外无返回结果控制台报错的问题现在我修复下。

**Comment by 195680144195** [comment]
> > 
> 
> 有些插件的消息信息可能不是通过CommandSender#sendMessage发送的。导致执行结果不会被返回..另外无返回结果控制台报错的问题现在我修复下。

挺多插件的指令都不行，基本上就ess的指令都正常，其他的不行

**Comment by 195680144195** [comment]
> > 
> 
> 有些插件的消息信息可能不是通过CommandSender#sendMessage发送的。导致执行结果不会被返回..另外无返回结果控制台报错的问题现在我修复下。

就很奇怪，有些指令会打印在控制台，Rcon issued server command: /list，可以用
有些指令不会打印在控制台但是能用，
有些指令打印在控制台也没用。

**Comment by 195680144195** [comment]
我发现这个插件似乎是每发送一条指令都会尝试连接一次rcon，控制台提示rcon启动
连续执行了很多次指令后
然后就控制台就提示很多次断开rcon连接，
这个rcon难道不是连接后一直保持连接然后执行指令的吗？

**Comment by smallXueTu** [comment]
> 我发现这个插件似乎是每发送一条指令都会尝试连接一次rcon，控制台提示rcon启动 连续执行了很多次指令后 然后就控制台就提示很多次断开rcon连接， 这个rcon难道不是连接后一直保持连接然后执行指令的吗？

一直保持链接不太现实 因为用户可能会长达几天不会执行命令 关于关闭资源这点好像确实忽略了

**Comment by smallXueTu** [comment]
> > 我发现这个插件似乎是每发送一条指令都会尝试连接一次rcon，控制台提示rcon启动 连续执行了很多次指令后 然后就控制台就提示很多次断开rcon连接， 这个rcon难道不是连接后一直保持连接然后执行指令的吗？
> 
> 一直保持链接不太现实 因为用户可能会长达几天不会执行命令 关于关闭资源这点好像确实忽略了

每次执行命令后会关闭链接 记错了

**Comment by smallXueTu** [comment]
两个问题已经修复了[https://github.com/smallXueTu/Rcon/releases/tag/v2.0.1-SR2](https://github.com/smallXueTu/Rcon/releases/tag/v2.0.1-SR2)
